import React, { useState } from 'react';
import { X, FileText, Download, Calendar, Check, Loader2 } from 'lucide-react';
import jsPDF from 'jspdf';
interface ReportGeneratorProps {
  isOpen: boolean;
  onClose: () => void;
  reportType?: string;
}
const REPORT_TYPES = [
{
  id: 'users',
  label: 'User Activity Report',
  desc: 'New registrations, active users, and role distribution'
},
{
  id: 'properties',
  label: 'Property Listings Report',
  desc: 'Verification status, property types, and location stats'
},
{
  id: 'bookings',
  label: 'Booking Summary',
  desc: 'Revenue, occupancy rates, and booking trends'
},
{
  id: 'financial',
  label: 'Financial Statement',
  desc: 'Detailed revenue breakdown and commission earnings'
},
{
  id: 'security',
  label: 'Security Audit Log',
  desc: 'Login attempts, system changes, and security alerts'
}];

export function ReportGenerator({
  isOpen,
  onClose,
  reportType = ''
}: ReportGeneratorProps) {
  const [selectedType, setSelectedType] = useState(reportType || 'users');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);
  if (!isOpen) return null;
  const generatePDF = () => {
    setIsGenerating(true);
    // Simulate processing time
    setTimeout(() => {
      const doc = new jsPDF();
      const timestamp = new Date().toLocaleString();
      const reportName =
      REPORT_TYPES.find((t) => t.id === selectedType)?.label || 'Report';
      // Header
      doc.setFillColor(22, 22, 22); // #161616
      doc.rect(0, 0, 210, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.text('FindItMate Admin', 20, 20);
      doc.setFontSize(12);
      doc.setTextColor(200, 200, 200);
      doc.text('CONFIDENTIAL REPORT', 20, 30);
      // Report Info
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(18);
      doc.text(reportName, 20, 60);
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated on: ${timestamp}`, 20, 70);
      doc.text(`Generated by: System Administrator`, 20, 75);
      // Content based on type
      let yPos = 90;
      // Table Header
      doc.setFillColor(240, 240, 240);
      doc.rect(20, yPos - 5, 170, 10, 'F');
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      doc.setFont('helvetica', 'bold');
      if (selectedType === 'users') {
        doc.text('ID', 25, yPos);
        doc.text('Name', 45, yPos);
        doc.text('Email', 90, yPos);
        doc.text('Role', 150, yPos);
        doc.text('Status', 180, yPos);
        // Mock Data Rows
        doc.setFont('helvetica', 'normal');
        const users = [
        {
          id: '001',
          name: 'John Doe',
          email: 'john@example.com',
          role: 'Admin',
          status: 'Active'
        },
        {
          id: '002',
          name: 'Jane Smith',
          email: 'jane@host.com',
          role: 'Landlord',
          status: 'Active'
        },
        {
          id: '003',
          name: 'Mike Johnson',
          email: 'mike@host.com',
          role: 'Landlord',
          status: 'Pending'
        },
        {
          id: '004',
          name: 'Sarah Wilson',
          email: 'sarah@student.com',
          role: 'Student',
          status: 'Active'
        },
        {
          id: '005',
          name: 'Tom Brown',
          email: 'tom@student.com',
          role: 'Student',
          status: 'Suspended'
        }];

        users.forEach((user, i) => {
          yPos += 10;
          doc.text(user.id, 25, yPos);
          doc.text(user.name, 45, yPos);
          doc.text(user.email, 90, yPos);
          doc.text(user.role, 150, yPos);
          doc.text(user.status, 180, yPos);
          // Row line
          doc.setDrawColor(230, 230, 230);
          doc.line(20, yPos + 3, 190, yPos + 3);
        });
      } else {
        // Generic content for other types
        doc.text('Item', 25, yPos);
        doc.text('Description', 60, yPos);
        doc.text('Date', 140, yPos);
        doc.text('Value', 180, yPos);
        doc.setFont('helvetica', 'normal');
        for (let i = 1; i <= 5; i++) {
          yPos += 10;
          doc.text(`Item #${i}`, 25, yPos);
          doc.text(`Sample data entry for ${selectedType} report`, 60, yPos);
          doc.text('2024-05-20', 140, yPos);
          doc.text('LKR 1,250.00', 180, yPos);
          doc.setDrawColor(230, 230, 230);
          doc.line(20, yPos + 3, 190, yPos + 3);
        }
      }
      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text('FindItMate Platform - Internal Use Only', 105, 280, {
        align: 'center'
      });
      doc.text('Page 1 of 1', 190, 280, {
        align: 'right'
      });
      doc.save(`finditmate-${selectedType}-report.pdf`);
      setIsGenerating(false);
      setIsSuccess(true);
      setTimeout(() => {
        setIsSuccess(false);
        onClose();
      }, 2000);
    }, 1500);
  };
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
      <div className="w-full max-w-2xl bg-[#161616] border border-[#333] rounded-2xl overflow-hidden shadow-2xl">
        <div className="p-6 border-b border-[#333] flex justify-between items-center">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-[#222] rounded-lg border border-[#333]">
              <FileText className="w-6 h-6 text-white" />
            </div>
            <h2 className="text-xl font-bold text-white">Generate Report</h2>
          </div>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-white transition-colors">

            <X className="w-6 h-6" />
          </button>
        </div>

        <div className="p-6">
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-400 mb-2">
              Select Report Type
            </label>
            <div className="space-y-2">
              {REPORT_TYPES.map((type) =>
              <button
                key={type.id}
                onClick={() => setSelectedType(type.id)}
                className={`w-full text-left p-4 rounded-xl border transition-all flex items-start gap-3 ${selectedType === type.id ? 'bg-red-900/10 border-red-600' : 'bg-[#0f0f0f] border-[#333] hover:border-[#555]'}`}>

                  <div
                  className={`mt-1 w-4 h-4 rounded-full border flex items-center justify-center ${selectedType === type.id ? 'border-red-600' : 'border-gray-500'}`}>

                    {selectedType === type.id &&
                  <div className="w-2 h-2 rounded-full bg-red-600" />
                  }
                  </div>
                  <div>
                    <h4
                    className={`font-medium ${selectedType === type.id ? 'text-white' : 'text-gray-300'}`}>

                      {type.label}
                    </h4>
                    <p className="text-sm text-gray-500">{type.desc}</p>
                  </div>
                </button>
              )}
            </div>
          </div>

          <div className="bg-[#0f0f0f] rounded-xl p-4 border border-[#333] mb-6">
            <h4 className="text-sm font-bold text-white mb-3">
              Report Preview
            </h4>
            <div className="space-y-2 text-sm text-gray-400">
              <div className="flex justify-between">
                <span>Format:</span>
                <span className="text-white">PDF Document (.pdf)</span>
              </div>
              <div className="flex justify-between">
                <span>Includes:</span>
                <span className="text-white">Charts, Data Tables, Summary</span>
              </div>
              <div className="flex justify-between">
                <span>Date Range:</span>
                <span className="text-white">Last 30 Days</span>
              </div>
            </div>
          </div>

          <div className="flex gap-3">
            <button
              onClick={onClose}
              className="flex-1 px-4 py-3 bg-[#222] hover:bg-[#333] text-white rounded-xl font-medium transition-colors border border-[#333]">

              Cancel
            </button>
            <button
              onClick={generatePDF}
              disabled={isGenerating || isSuccess}
              className={`flex-1 px-4 py-3 rounded-xl font-medium transition-all flex items-center justify-center gap-2 ${isSuccess ? 'bg-green-600 text-white' : 'bg-red-600 hover:bg-red-700 text-white shadow-lg shadow-red-900/20'}`}>

              {isGenerating ?
              <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Generating...
                </> :
              isSuccess ?
              <>
                  <Check className="w-5 h-5" />
                  Downloaded!
                </> :

              <>
                  <Download className="w-5 h-5" />
                  Generate & Download PDF
                </>
              }
            </button>
          </div>
        </div>
      </div>
    </div>);

}